use std::sync::OnceLock;
use crate::logger::info;
use crate::utils::dom::create_data_url;
use crate::utils::time::now;
use js_sys::{Function, Reflect, Uint8Array};
use lzma_rs::xz_decompress;
use serde_derive::Deserialize;
use serde_json::Value;
use wasm_bindgen::prelude::*;
use web_sys::{Document, Element};
use crate::base::asset::{Asset, Export};
use crate::js_err;
use crate::studio::components::text_editor::get_ace;

const SHADER_PREAMBLE: &str = "// Generated by MojoShader via WebAssetStudio.\
\n// https://github.com/icculus/MojoShader\n\n";

const WASM_XZ: &[u8] = include_bytes!("mojoshader.wasm.xz");
const JS: &str = include_str!("mojoshader.js");
static MODULE: OnceLock<MojoShader> = OnceLock::new();

#[derive(Deserialize, Debug)]
pub struct ParseError {
    pub error: String,
    pub position: i32,
    pub filename: String
}

#[derive(Deserialize, Debug)]
pub struct EffectState {
    pub r#type: i32,
    pub value: EffectValue
}

#[derive(Deserialize, Debug)]
pub struct EffectPass {
    pub name: String,
    pub states: Vec<EffectState>,
    pub annotations: Vec<EffectValue>
}

#[derive(Deserialize, Debug)]
pub struct EffectTechnique {
    pub name: String,
    pub passes: Vec<EffectPass>,
    pub annotations: Vec<EffectValue>
}

#[derive(Deserialize, Debug)]
pub struct ShaderSymbol {
    pub name: String,
    pub register_set: String,
    pub register_index: i32,
    pub register_count: i32,
    pub type_info: TypeInfo
}

#[derive(Deserialize, Debug)]
#[serde(tag = "type", rename_all = "lowercase")]
pub enum PreShaderOperand {
    Literal { value: Vec<f64> },
    Input { index: i32, array_registers: Vec<i32> },
    Output { index: i32, array_registers: Vec<i32> },
    Temp { index: i32, array_registers: Vec<i32> }

}

#[derive(Deserialize, Debug)]
pub struct PreShaderInstruction {
    pub opcode: String,
    pub operands: Vec<PreShaderOperand>
}

#[derive(Deserialize, Debug)]
pub struct PreShader {
    pub symbols: Vec<ShaderSymbol>,
    pub instructions: Vec<PreShaderInstruction>
}

#[derive(Deserialize, Debug)]
pub struct ShaderObject {
    pub is_preshader: i32,
    pub technique: u32,
    pub pass: u32,
    pub preshader: Option<PreShader>,
    #[serde(flatten)]
    pub shader: ShaderResult
}

#[derive(Deserialize, Debug)]
pub struct ShaderAttribute {
    pub name: String,
    pub index: i32,
    pub usage: String
}

#[derive(Deserialize, Debug)]
#[serde(untagged)]
pub enum ShaderConstantValue {
    Int(Vec<i32>),
    Float(Vec<f64>),
    Bool(i32),
    Null
}

#[derive(Deserialize, Debug)]
pub struct ShaderConstant {
    pub index: i32,
    pub r#type: String,
    pub value: ShaderConstantValue
}

#[derive(Deserialize, Debug)]
pub struct ShaderUniform {
    pub name: String,
    pub r#type: String,
    pub constant: bool,
    pub index: i32,
    pub array_count: i32
}

#[derive(Deserialize, Debug)]
pub struct ShaderSampler {
    pub index: i32,
    pub name: String,
    pub r#type: String,
    pub texbem: bool
}

#[derive(Deserialize, Debug)]
pub struct Shader {
    pub r#type: String,
    pub version: Vec<i32>,
    pub instruction_count: i32,
    pub main_function: String,
    pub inputs: Vec<ShaderAttribute>,
    pub outputs: Vec<ShaderAttribute>,
    pub constants: Vec<ShaderConstant>,
    pub uniforms: Vec<ShaderUniform>,
    pub samplers: Vec<ShaderSampler>,
    pub symbols: Vec<ShaderSymbol>,
    pub preshader: Option<PreShader>,
    pub output: Option<String>,
    pub profile: String
}

#[derive(Deserialize, Debug)]
pub struct ShaderResult {
    pub errors: Option<Vec<ParseError>>,
    #[serde(rename = "shader")]
    pub result: Option<Shader>
}

#[derive(Deserialize, Debug)]
#[serde(tag = "type", rename_all = "lowercase")]
pub enum EffectObject {
    Void {},
    Bool { value: i32 },
    Int { value: i32 },
    Float { value: f32 },
    String { value: String },
    Texture {},
    Texture1D {},
    Texture2D {},
    Texture3D {},
    TextureCube {},
    Sampler {},
    Sampler1D {},
    Sampler2D {},
    Sampler3D {},
    SamplerCube {},
    PixelShader { value: ShaderObject },
    VertexShader { value: ShaderObject },
}

#[derive(Deserialize, Debug)]
pub struct EffectParam {
    pub value: EffectValue,
    pub annotations: Vec<EffectValue>
}

#[derive(Deserialize, Debug)]
pub struct SymbolStructMember {
    pub name: String,
    pub info: TypeInfo
}

#[derive(Deserialize, Debug)]
pub struct TypeInfo {
    pub param_class: String,
    pub param_type: String,
    pub rows: i32,
    pub columns: i32,
    pub elements: i32,
    pub members: Vec<SymbolStructMember>
}

#[derive(Deserialize, Debug)]
pub struct SamplerState {
    pub r#type: String,
    pub value: f64
}

#[derive(Deserialize, Debug)]
#[serde(untagged)]
pub enum EffectValueData {
    Value(Vec<f64>),
    Sampler(Vec<SamplerState>)
}

#[derive(Deserialize, Debug)]
pub struct EffectValue {
    pub name: String,
    pub semantic: String,
    pub r#type: TypeInfo,
    pub num_values: i32,
    pub values: EffectValueData
}

#[derive(Deserialize, Debug)]
pub struct Effect {
    pub objects: Vec<EffectObject>,
    pub params: Vec<EffectParam>,
    pub techniques: Vec<EffectTechnique>,
    pub errors: Vec<ParseError>
}

impl Asset for Effect {
    fn make_html(&mut self, doc: &Document, parent: &Element) -> anyhow::Result<()> {
        let container = doc.create_element("div").unwrap();
        container.set_id("shader-src");
        parent.append_child(&container).unwrap();
        for object in &self.objects {
            match object {
                EffectObject::PixelShader { value: p } | EffectObject::VertexShader { value: p } => {
                    let ace = get_ace();
                    let editor = ace.edit("shader-src");
                    editor.set_mode("ace/mode/glsl");
                    editor.set_theme("ace/theme/tomorrow_night");
                    editor.set_value(&format!("{}{}", SHADER_PREAMBLE, p.shader.result.as_ref().unwrap().output.as_ref().unwrap()));
                    editor.set_readonly(true);
                    editor.select_none();
                    break;
                },
                _ => {}
            }
        }
        Ok(())
    }

    fn export(&mut self) -> Export {
        todo!()
    }
}

#[derive(Debug)]
pub struct MojoShader {
    module: JsValue
}

impl MojoShader {
    pub fn parse(&self, shader: &[u8], profile: &str) -> anyhow::Result<Effect> {
        let malloc = Function::from(js_err!(Reflect::get(&self.module, &JsValue::from_str("_malloc")))?);
        let free = Function::from(js_err!(Reflect::get(&self.module, &JsValue::from_str("_free")))?);
        let parse = Function::from(js_err!(Reflect::get(&self.module, &JsValue::from_str("_parse")))?);
        let heap = Uint8Array::from(js_err!(Reflect::get(&self.module, &JsValue::from_str("HEAPU8")))?);

        let profile_ptr = js_err!(malloc
            .call1(&JsValue::undefined(), &JsValue::from(profile.len() + 1))
        )?;
        let profile_ptr_u32 = profile_ptr.as_f64().unwrap() as u32;
        heap.set_index(profile_ptr_u32 + (profile.len() as u32), 0);
        let mut i = 0;
        for c in profile.chars() {
            heap.set_index(profile_ptr_u32 + i, c as u8);
            i += 1;
        }
        let data_ptr = malloc
            .call1(&JsValue::undefined(), &JsValue::from(shader.len()))
            .unwrap();
        heap.set(&Uint8Array::from(shader), data_ptr.as_f64().unwrap() as u32);

        let ptr = parse.call3(&JsValue::undefined(), &data_ptr, &JsValue::from(shader.len()), &profile_ptr).unwrap().as_f64().unwrap() as u32;
        let mut s = "".to_owned();
        let mut b = 0xff;
        let mut i = 0;
        loop {
            b = heap.get_index(ptr + i);
            if b == 0 {
                break;
            }
            s.push(char::from(b));
            i += 1;
        }

        js_err!(free.call1(&JsValue::undefined(), &profile_ptr))?;
        js_err!(free.call1(&JsValue::undefined(), &data_ptr))?;

        let jd = &mut serde_json::Deserializer::from_str(&s);

        let result: Result<Effect, _> = serde_path_to_error::deserialize(jd);
        Ok(result?)
    }
}

unsafe impl Sync for MojoShader {}
unsafe impl Send for MojoShader {}

pub fn get_mojoshader<'a>() -> &'a MojoShader {
    if let Some(m) = MODULE.get() {
        return m;
    }
    let start = now();
    let mut res = Vec::new();
    xz_decompress(&mut WASM_XZ, &mut res).unwrap();
    let data_url = create_data_url(&res[..], "application/wasm");
    // replace the path in our js module
    let js = JS.replace("\"mojoshader.wasm\"", &format!("\"{data_url}\""));
    let func = Function::new_no_args(&format!("{};return Module;", js));
    let module = func.call0(&JsValue::undefined()).unwrap();

    let module = MojoShader { module };
    MODULE.set(module).unwrap();

    let elapsed = now() - start;
    info!("Loaded MojoShader in {} ms", elapsed);
    MODULE.get().unwrap()
}
