struct GeneralInfoChunk {
    debugger_disabled: bool,
    format_version: i32,
    file_name: String,
    configuration: String,
    max_room_id: i32,
    max_room_tile_id: i32,
    game_id: i32,
    reserved: [i32; 4],
    game_name: String,
    major_version: i32,
    minor_version: i32,
    release_version: i32,
    build_version: i32,
    initial_width: i32,
    initial_height: i32,
    flags: i32,
    license_checksum: u32,
    license_hash: [u32; 4],
    timestamp: u64,
    display_name: String,
    active_targets: u64,
    function_categories: u64,
    steam_app_id: i32,
    debugger_port: i32,
    room_order: Vec<i32>,
    build_hash: [u32; 10],
    game_speed: f32,
    allow_stats: bool,
    game_guid: [u32; 4]
}
