name: webassetstudio-build
run-name: Build and deploy
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      # - name: Build main WASM (FUTURE)
      #   run: wasm-pack build
      # TODO: add MojoShader build script when the rewrite is complete
      - name: Build encoders
        run: cd encoders && wasm-pack build --out-dir ../js/encoders
      - name: Install dependencies
        run: npm install
      - name: Build web
        run: npm run build
      - name: Deploy to server
        run: sshpass -p ${{ secrets.SSH_PASS }} scp -P ${{ secrets.SSH_PORT }} -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r dist ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.WORK_DIR }}/
      - name: Cleanup
        run: rm -rf ~/.ssh && rm -rf dist